# ukljucuje GPIO subsistem => mozes da koristis:
# gpio_pin_configure_dt()
# gpio_pin_configure_dt()
# gpio_pin_interrupt_configure_dt()
# BEZ OVOGA NE BI MOGAO DA KORISTIS #include <zephyr/drivers/gpio.h>
# ovo kaze zephyr buiild sistemu da ukljuci GPIO API + odgovarajuci GPIO drajver za odgovarajuci board/soc!!!!!!!!!!!!!!!!!!!!!!!!
# kad u kodu pozoves gpio_pin_toggle_dt(&led); => da nza da je u pitanju GPIOA sa pinom 5
CONFIG_GPIO=y

#omogucava printk() za ispisvanje
CONFIG_PRINTK=y

#podesava stack size za main thread
# kernel pokrece main() kao thread, i main ima svoj stack
CONFIG_MAIN_STACK_SIZE=1024

#comment out if you want to use the default optimization which is -Os (optimize for size)
CONFIG_SPEED_OPTIMIZATIONS=y
